/* eslint-disable @next/next/no-img-element */
import Head from "next/head";
import { FormEvent, useState } from "react";
import { useLogStore } from "../stores/logStore";
var pluralize = require("pluralize");

export default function Home() {
  const [fileContent, setFileContent] = useState<string[]>([]);
  const { logInformation, analyzeLog } = useLogStore();
  const [errorMessage, setErrorMessage] = useState<string>("");

  const handleSubmit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();

    const fileInput = event.currentTarget.querySelector(
      'input[type="file"]'
    ) as HTMLInputElement;
    const file = fileInput?.files?.[0];

    const reader = new FileReader();

    reader.onload = (e) => {
      const contents = e.target?.result as string;
      const lines = contents.split("\n");
      setFileContent(lines);
    };

    reader.readAsText(file as Blob);
  };

  //Gets a list of HTML nodes based on CreatureKind list
  let creatureList = [];
  for (let [
    key,
    value
  ] of logInformation.damageTaken.byCreatureKind.entries()) {
    creatureList.push(
      <li key={key + value.toString()} className="flex items-center">
        <img
          alt="" //Decorative Image Only
          src={`https://static.tibia.com/images/library/${key
            .replace(/\s/g, "")
            .toLowerCase()}.gif`}
        />
        <p>
          By {key.replace(/(?:^|\s)\S/g, (a) => a.toUpperCase())}: {value}hp
        </p>
      </li>
    );
  }

  let lootList = [];
  for (let [key, value] of logInformation.loot.entries()) {
    lootList.push(
      <li key={key + value.toString()} className="flex items-center">
        <img
          alt="" //Decorative Image Only
          src={`https://www.tibiawiki.com.br/images/e/ef/Brocade_Bag.gif`}
        />
        <p>
          {value}{" "}
          {pluralize(
            key.replace(/(?:^|\s)\S/g, (a) => a.toUpperCase()),
            value
          )}
        </p>
      </li>
    );
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-4">
        <h1 className="text-4xl text-primary-400">TibiAnalyser</h1>

        <br />

        <section>
          <button
            onClick={() => {
              const res = analyzeLog(fileContent);

              if (res) setErrorMessage(res.body);
              else setErrorMessage("");
            }}
            className="rounded-md bg-neutral-600 px-4 py-2"
          >
            Analyse
          </button>
          {errorMessage && <p className="text-red-400">{errorMessage}</p>}
          <ul>
            <li className="flex items-center">
              <img
                src="https://www.tibiawiki.com.br/images/9/91/Great_Health_Potion.gif"
                alt="" //Decorative Image Only
              />
              <p>Hitpoints Healed Total: {logInformation.hitpointsHealed}hp</p>
            </li>
            <li className="flex items-center">
              <img
                src="https://www.tibiawiki.com.br/images/c/c4/Stonecutter_Axe.gif"
                alt="" //Decorative Image Only
              />
              <p>Damage Taken Total: {logInformation.damageTaken.total}hp</p>
            </li>
            <ul>{creatureList}</ul>
            <li className="flex items-center">
              <img
                src="https://www.tibiawiki.com.br/images/b/b2/Achievement_Info_1-1.gif"
                alt="" //Decorative Image Only
              />
              <p>
                Experience Gained Total: {logInformation.experienceGained}xp
              </p>
            </li>
            <div className="flex">
              <img
                alt=""
                src="https://www.tibiawiki.com.br/images/d/d8/Brocade_Backpack.gif"
              />
              <p>List of Items</p>
            </div>
            <ul>{lootList}</ul>
          </ul>
        </section>

        <br />

        <section>
          <h1>Upload a TXT file</h1>
          <form onSubmit={handleSubmit}>
            <input type="file" />
            <button
              type="submit"
              className="rounded-md bg-neutral-600 px-4 py-2"
            >
              Upload
            </button>
          </form>
          {fileContent.length > 0 && (
            <div>
              <h2>File Content:</h2>
              <ul>
                {fileContent.map((line, index) => (
                  <li key={index}>{line}</li>
                ))}
              </ul>
            </div>
          )}
        </section>
      </main>
    </>
  );
}
